- hosts: Web
  tasks:
  - name: Check that the somefile.conf exists
    stat:
      path: /home/ansible/file.txt
    register: stat_result

  - name: Create the file, if it doesnt exist already
    file:
      path: /home/ansible/file.txt 
      state: touch
    when: stat_result.stat.exists == False 

