- hosts: Web
  tasks:
    - copy:
          src: /home/ansible/scripts/healthcheck.sh
          dest: /home/ansible/healthcheck.sh

    - name: Execute the script to generate healthcheck of all ubuntu ansible servers
      command: sh /home/ansible/healthcheck.sh
